version: '3.7'
services:
  sensor:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: distance
    volumes:
      - demo:/data/
    ports:
      - "8000:8000"
    devices:
      - "/dev/ttyS0:/dev/ttyS0"
volumes:
  demo:
    external: true