version: '3.7'
services:
  surface_sensor_01:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: distancesensor
    volumes:
      - demo:/data/
    ports:
      - "8000:8000"

volumes:
  demo:
    external: true